packages:
  # all packages in direct subdirs of packages/
  - 'packages/@cmsonfire/*'
  # all packages in subdirs of components/
  # - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'